name: Deploy to Neocities

on:
  push:
    branches:
      - main # Change to 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        dist_dir: 'public'
        cleanup: false 
